<?php
if ( ! defined( 'ABSPATH' ) ) exit; // Exit if accessed directly

// autoload_real.php @generated by Composer

class ComposerAutoloaderInitb555cff54c4b49e38e71715dd8e16bdc
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInitb555cff54c4b49e38e71715dd8e16bdc', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInitb555cff54c4b49e38e71715dd8e16bdc', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInitb555cff54c4b49e38e71715dd8e16bdc::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
